setwd("/Users/xiaoyuzhou/Dropbox/Rscripts/CAR-CT_sc")
library(Seurat)
library(dplyr)
library(patchwork)
library(umap)
library(ggplot2)
library(BiocParallel)
library(SeuratWrappers)
library(BiocManager)
library(remotes)
library(devtools)
library(clusterProfiler)
library(enrichplot)
library(ggrepel)

##read in data generated by Cellranger
CARCT_all.data <- Read10X(data.dir = "/Users/xiaoyuzhou/Dropbox/Rscripts/CAR-CT_sc/filtered_feature_bc_matrix")

## Initialize the Seurat object with the raw (non-normalized data).
CARCT <- CreateSeuratObject(counts = CARCT_all.data, project = "CAR", min.cells = 3, min.features = 200)
CARCT[["percent.mt"]] <- PercentageFeatureSet(CARCT, pattern = "^MT-")

##Adding metadata
sample_names <- c('BM_39A','BM_39B','BM_39C','BM_39D','SP_39A','SP_39B','SP_39C','SP_39D')
sample_tissue <- c(rep('BM',4),rep('Spleen',4))
CT_number <- c(0:3, 0:3)
CARCT[['SampleNumber']] <- stringr::str_split(rownames(CARCT@meta.data),'-',simplify = T)[,2]
CARCT[['Sample']] <- sample_names[as.integer(CARCT[['SampleNumber']]$SampleNumber)]
CARCT[["tissue"]] <- sample_tissue[as.integer(CARCT[['SampleNumber']]$SampleNumber)]
CARCT[["CT_number"]] <- CT_number[as.integer(CARCT[['SampleNumber']]$SampleNumber)]
head(CARCT@meta.data)

##Visulize QC metrics
qc_plot <- VlnPlot(CARCT, group.by = 'orig.ident', 
        features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), 
        ncol = 3, pt.size = 0)
ggsave(qc_plot, height = 6, width = 6, filename = "qc_plot.pdf")

##Save unfiltered data
saveRDS(CARCT, file = "CARCT_unfiltered.rds")
CARCT <- readRDS(file = "CARCT_unfiltered.rds")

##filter dataset
CARCT <- subset(CARCT, subset = nFeature_RNA > 200 &
                  nFeature_RNA < 2500 & percent.mt < 10)
saveRDS(CARCT, file = "CARCT_filtered.rds")

##Normalization
CARCT <- NormalizeData(CARCT, normalization.method = "LogNormalize", scale.factor = 10000)

##Normalization
#CARCT <- NormalizeData(CARCT, normalization.method = "LogNormalize", scale.factor = 10000)

##Identification of highly variable features
CARCT <- FindVariableFeatures(CARCT, selection.method = "vst", nfeatures = 2000)

##Identify the 10 most highly variable genes
top10 <- head(VariableFeatures(CARCT), 10)
plot1 <- VariableFeaturePlot(CARCT)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
plot3 <- plot1 + plot2
ggsave(plot3, height = 6, width = 12,filename = "highly_variable_genes_top10.pdf")

##Scaling the data
all.genes <- rownames(CARCT)
#the default in ScaleData() is only to perform scaling on the 
#previously identified variable features (2,000 by default).
#for scaling all genes 
#CARCT <- ScaleData(CARCT, features = all.genes)
CARCT <- ScaleData(CARCT)
saveRDS(CARCT, file = "CARCT_scaled.rds")

##linear dimensional reduction
CARCT <- RunPCA(CARCT, features = VariableFeatures(object = CARCT))
saveRDS(CARCT, file = "CARCT_PCA.rds")
CARCT <- readRDS(file = "CARCT_PCA.rds")
#DimHeatmap(CARCT, dims = 3, cells = 500, balanced = TRUE)

#Determine PC number
ElbowPlot(CARCT)

##clustering
CARCT <- RunUMAP(CARCT, dims = 1:10)
CARCT <- FindNeighbors(CARCT, dims = 1:10)
CARCT <- FindClusters(CARCT, resolution = 0.2)
DimPlot(CARCT,reduction = "umap", label = T)
#subclustering of cluster 3
Idents(CARCT) <- CARCT[['RNA_snn_res.0.2']]
CARCT <- FindSubCluster(CARCT, graph.name = "RNA_snn",resolution = 0.1, cluster = "3", subcluster.name = "a3")
Idents(CARCT) <- CARCT[['a3']]

#subclustering of cluster 1
CARCT <- FindSubCluster(CARCT, graph.name = "RNA_snn",resolution = 0.1, cluster = "1", subcluster.name = "a1")
Idents(CARCT) <- CARCT[['a1']]

#subclustering of cluster 0
#CARCT <- FindSubCluster(CARCT, graph.name = "RNA_snn",resolution = 0.1, cluster = "0", subcluster.name = "a0")
#Idents(CARCT) <- CARCT[['a0']]

#subclustering of cluster 2
CARCT <- FindSubCluster(CARCT, graph.name = "RNA_snn",resolution = 0.22, cluster = "2", subcluster.name = "a2")
Idents(CARCT) <- CARCT[['a2']]


#order the labels of clusters
CARCT[['a2']] <- factor(CARCT[['a2']]$a2, levels = sort(unique(CARCT[['a2']]$a2)))
Idents(CARCT) <- CARCT[['a2']]

saveRDS(CARCT, file = "CARCT_cluster_20230130.rds")
CARCT <- readRDS(file = "CARCT_cluster_20230130.rds")
#remove cluster 6 and 7(PTPRC low population)
CARCT_sub <- subset(CARCT, idents = c(6, 7), invert = T)
head(Idents(CARCT))
##group by sample type
#change sample order
#CARCT[['Sample']] <- factor(CARCT[['Sample']]$Sample, 
                            #levels = c("BM_39A", "BM_39B", "BM_39C", "BM_39D", "SP_39A", "SP_39B", "SP_39C","SP_39D"))

cluster_plot1 <- DimPlot(CARCT_sub,reduction = "umap", group.by = 'Sample', 
                         order = c( "BM_39A", "BM_39B", "BM_39C", "BM_39D","SP_39A", "SP_39B", "SP_39C","SP_39D"),
                         pt.size = 0.02,
                         shuffle = T,
                         cols = c( "#426df5","#8ca5f5","#b3c3f5", "#d2dcf7", 
                                  "#f54242","#f56969","#f28a8a","#f0adad"))
ggsave(cluster_plot1, height = 6, width = 6,filename = "Cluster_byGroup.pdf")


##group by cluster
cluster.p1 <- DimPlot(CARCT_sub,reduction = "umap", 
                      cols = c("#F8766D", "#d3b0f5", "#e900ff", "#3679f5", "#f78fcb",
                               "#00BFC4" , "#D89000", "#7d79c7",  "#39B600", "#2c00f0"))
ggsave(cluster.p1, height = 6, width = 6,filename = "Cluster_byCluster_2.pdf")
#Split by conditions

##highlight one of the datasets
p1 <- DimPlot(CARCT,reduction = "umap", pt.size = 0.02, cols.highlight = "#f56969",
        cells.highlight = rownames(CARCT@meta.data[which(CARCT@meta.data$Sample == 'BM_39A'),]))
p2 <- DimPlot(CARCT,reduction = "umap", pt.size = 0.02, cols.highlight = "#f56969",
              cells.highlight = rownames(CARCT@meta.data[which(CARCT@meta.data$Sample == 'BM_39B'),]))
p3 <- DimPlot(CARCT,reduction = "umap", pt.size = 0.02, cols.highlight = "#f56969",
              cells.highlight = rownames(CARCT@meta.data[which(CARCT@meta.data$Sample == 'BM_39C'),]))
p4 <- DimPlot(CARCT,reduction = "umap", pt.size = 0.02, cols.highlight = "#f56969",
              cells.highlight = rownames(CARCT@meta.data[which(CARCT@meta.data$Sample == 'BM_39D'),]))
p5 <- DimPlot(CARCT,reduction = "umap", pt.size = 0.02, cols.highlight = "#426df5",
              cells.highlight = rownames(CARCT@meta.data[which(CARCT@meta.data$Sample == 'SP_39A'),]))
p6 <- DimPlot(CARCT,reduction = "umap", pt.size = 0.02, cols.highlight = "#426df5",
              cells.highlight = rownames(CARCT@meta.data[which(CARCT@meta.data$Sample == 'SP_39B'),]))
p7 <- DimPlot(CARCT,reduction = "umap", pt.size = 0.02, cols.highlight = "#426df5",
              cells.highlight = rownames(CARCT@meta.data[which(CARCT@meta.data$Sample == 'SP_39C'),]))
p8 <- DimPlot(CARCT,reduction = "umap", pt.size = 0.02, cols.highlight = "#426df5",
              cells.highlight = rownames(CARCT@meta.data[which(CARCT@meta.data$Sample == 'SP_39D'),]))
ggsave(plot = p1+p2+p3+p4, '/CAR-CT_sc/cluster_BM.pdf')
ggsave(plot = p5+p6+p7+p8, '/CAR-CT_sc/cluster_SP.pdf')

##feature plots
p <- FeaturePlot(CARCT_sub,order = T,min.cutoff = 'q01', max.cutoff = 'q99', 
                 raster = T, features = c("SELL", "CD44", "MKI67", "CD4", "TCF7", "PTPRC", "IL7R", "GZMK",
                               "CD8A"))
ggsave(plot = p, '/Users/xiaoyuzhou/Dropbox/Rscripts/CAR-CT_sc/feature_plot.pdf')

##Find differential expressed features
# find all markers of cluster 6
cluster6.markers <- FindMarkers(CARCT, ident.1 = 5, min.pct = 0.25)
cluster6.markers$gene_name <- row.names(cluster6.markers)

# find differentially expressed markers between 6 and 7 clusters
cluster3.0_vs_1.0_markers <- FindMarkers(CARCT, ident.1 = "3_0", ident.2 = "1_0", min.pct = 0.25)
cluster3.0_vs_1.0_markers$gene_name <- row.names(cluster3.0_vs_1.0_markers)

cluster1_vs_2_markers <- FindMarkers(CARCT, ident.1 = 1, ident.2 = 2, min.pct = 0.25)
cluster1_vs_2_markers$gene_name <- row.names(cluster1_vs_2_markers)

# find markers for every cluster compared to all remaining cells, report only the positive
# ones
CARCT.markers <- FindAllMarkers(CARCT_sub, only.pos = F, min.pct = 0.25, 
                                logfc.threshold = 0.25, max.cells.per.ident = 1000)
CARCT.markers %>%
  group_by(cluster) %>%
  top_n(n = 10, wt = avg_log2FC) -> top10
htmap <- DoHeatmap(subset(CARCT_sub, downsample = 100), features = top10$gene, ) 

ggsave(plot = htmap,height = 9, width = 8, "htmap_12clusters.pdf")


## label the clusters
CARCT_sub <- RenameIdents(CARCT_sub, "0" = "CD8 Tcm1", "1_0" = "CD8 Tem","1_1" = "CD4 Tcm1",
                          "2_0" = "CD8 Trm","2_1" = "CD4 Teff", "2_2" = "CD4 Tcm2","2_3" = "CD8 Tcm2",
                          "3_0" = "CD8 Teff","3_1" = "CD4 Tem", "4" = "CD8 Tex like", 
                          "5" = "prolif. CD8 Tcm","8" = "CD8 Tscm")

Plot_labeled <- DimPlot(CARCT_sub, reduction = "umap",
        cols = c("#F8766D", "#d3b0f5", "#e900ff", "#3679f5", "#f78fcb",
                 "#00BFC4" , "#D89000", "#f77d02",  "#39B600", "#8166fa", "#bbd457", "#dbce12"),
        label = TRUE, pt.size = 0.5, label.box = T, repel = TRUE,label.size = 6,
        label.color = "black") 

ggsave(plot = Plot_labeled,height = 8, width = 8, "cluseters_labeled.pdf")

#Dimplot split by tissue type
Plot_tissue <- DimPlot(CARCT_sub, reduction = "umap", split.by = "tissue",
                       cols = c("#F8766D", "#d3b0f5", "#e900ff", "#3679f5", "#f78fcb",
                                "#00BFC4" , "#D89000", "#f77d02",  "#39B600", "#8166fa", "#bbd457", "#dbce12"))
ggsave(plot = Plot_tissue,height = 6, width =8, "cluseter_by_tissue.pdf")

##Vlnplot
Plot_Vln1 <-VlnPlot(CARCT_sub, features = c("CD4", "CD8A", "SELL", "TCF7","LEF1",
                                            "CD27", "CD28","CD226","GZMK", "PRF1",
                                             "ZNF683","TOX", "TIGIT","LAG3","MKI67"),
                    pt.size = 0, stack = T, flip = T)
#Plot_Vln1+ theme(axis.text.x = element_text(angle = 90))

ggsave(plot = Plot_Vln1 ,height = 8, width = 8, "Plot_Vln1.pdf")

##Cell type Abundance Bone marrow
table_BM <- CARCT_sub@meta.data[which(CARCT_sub$tissue=="BM"), ]

table_BM_count <- table_BM %>% group_by(CT_number, Celltype) %>% 
  summarise(Nb = n()) %>%
  mutate(C = sum(Nb)) %>%
  mutate(percent = Nb/C*100) 

library(ggplot2)

positions <- c("CD8 Tcm1", "CD8 Tcm2", "prolif. CD8 Tcm", "CD8 Tscm", "CD8 Trm", 
               "CD8 Tem", "CD8 Teff", "CD8 Tex like", "CD4 Tem", "CD4 Tcm1", "CD4 Tcm2", "CD4 Teff")
bar.percent <- ggplot(table_BM_count, aes(x = Celltype, y = percent, fill = factor(CT_number)))+
  geom_bar(stat = "identity", position = position_dodge())+
  scale_x_discrete(limits = positions)+ # reorder the bars

##facet bar plot
table_BM_count1 <- table_BM_count
table_BM_count1$Celltype <- factor(table_BM_count1$Celltype, 
                                   levels = c("CD8 Tcm1", "CD8 Tcm2", "prolif. CD8 Tcm", "CD8 Trm","CD8 Tscm",  
                                  "CD8 Tem", "CD8 Tex like","CD8 Teff","CD4 Tem", "CD4 Tcm1", "CD4 Tcm2", "CD4 Teff"))
bar_cell <- ggplot(table_BM_count1, aes(x = CT_number, y = percent))+
  geom_bar(stat = "identity", position = position_dodge(), fill = ggcolor(48))+
  facet_wrap(~Celltype, scales="free")+ theme_light()
ggsave(plot = bar_cell ,height = 5, width = 8, "bar_celltype.pdf")  

#pie chart
ggplot(table_BM_count, aes(x = "", y = percent, fill = Celltype))+
  geom_col() +
  coord_polar(theta = "y")+facet_wrap(~CT_number)
  
  #+scale_fill_manual(values = c("#F8766D", "#d3b0f5", "#e900ff", "#3679f5", "#f78fcb",
                               #"#00BFC4" , "#D89000", "#7d79c7",  "#39B600", "#2c00f0")) 
  

##Cell type Abundance Spleen
table_SP <- CARCT_sub@meta.data[which(CARCT_sub$tissue=="Spleen"), ]+

table_SP_count <- table_SP %>% group_by(CT_number, Celltype) %>% 
  summarise(Nb = n()) %>%
  mutate(C = sum(Nb)) %>%
  mutate(percent = Nb/C*100) 

#bar plot for spleen
bar.percent <- ggplot(table_SP_count, aes(x = Celltype, y = percent, fill = factor(CT_number)))+
  geom_bar(stat = "identity", position = position_dodge())+
  scale_x_discrete(limits = positions)
#pie chart for spleen
table_SP_count1 <- table_SP_count
table_SP_count1$Celltype <- factor(table_SP_count1$Celltype, 
                                   levels = c("CD8 Tcm1", "CD8 Tem","CD4 Tcm1","CD8 Trm", "CD4 Teff","CD4 Tcm2",
                                              "CD8 Tcm2", "CD8 Teff","CD4 Tem","CD8 Tex like","prolif. CD8 Tcm", "CD8 Tscm"))

pie_spleen <- ggplot(table_SP_count, aes(x = "", y = percent, fill = Celltype))+
  geom_col() +
  coord_polar(theta = "y")+facet_wrap(~CT_number)+
  scale_fill_manual(values=c("#fa8c84", "#d3b0f5","#3679f5","#f78fcb","#00BFC4" ,  
                              "#D89000", "#f77d02",  "#39B600", "#8166fa", "#bbd457", "#dbce12","#e900ff" ))
ggsave(plot = pie_spleen ,height = 8, width = 8, "pie_spleen.pdf")  

pie_BM <- ggplot(table_BM_count, aes(x = "", y = percent, fill = Celltype))+
  geom_col() +
  coord_polar(theta = "y")+facet_wrap(~CT_number)+
  scale_fill_manual(values=c("#fa8c84", "#d3b0f5","#e900ff" ,"#3679f5","#f78fcb","#00BFC4" ,  
                             "#D89000", "#f77d02",  "#39B600", "#8166fa", "#bbd457", "#dbce12"))
ggsave(plot = pie_BM ,height = 8, width = 8, "pie_BM.pdf")  

################################################Data Export#############################################

##Metadata
UMI <- as.data.frame(CARCT_sub@reductions$umap@cell.embeddings)
CARCT_sub_meta <- cbind(CARCT_sub@meta.data, UMI)
CARCT_sub_meta$Cell_barcode <- row.names(CARCT_sub_meta)
write.table(CARCT_sub_meta, "CARCT_sub_metadata.txt",
            quote=F, col.names=T, row.names=F, sep="\t")
##DEGs
write.table(CARCT.markers, "CARCT_DEGs.txt",
            quote=F, col.names=T, row.names=F, sep="\t")

##Celltype Proportion 
write.table(table_BM_count, "BM_perctage.txt",
            quote=F, col.names=T, row.names=F, sep="\t")
write.table(table_SP_count, "SP_perctage.txt",
            quote=F, col.names=T, row.names=F, sep="\t")

###############################################other analysis############################################


##DE expression across conditions within cluster
CARCT_sub_de <- CARCT_sub
CARCT_sub_de$celltyple.stim <- paste(Idents(CARCT_sub_de), CARCT_sub_de$CT_number, sep = "_")
CARCT_sub_de$celltype <- Idents(CARCT_sub_de)
Idents(CARCT_sub_de) <- CARCT_sub_de$celltyple.stim
saveRDS(CARCT_sub_de, file = "CARCT_sub_de.rds")
##subset SP samples
CARCT_sub_SP <- subset(x = CARCT_sub_de, subset = tissue == "Spleen")
#Tcm
Tcm_SP_ca <- FindMarkers(CARCT_sub_SP , ident.1 = "CD8 Tcm1_2", ident.2 = "CD8 Tcm1_0", verbose = FALSE)
Tcm_SP_ba <- FindMarkers(CARCT_sub_SP , ident.1 = "CD8 Tcm1_1", ident.2 = "CD8 Tcm1_0", verbose = FALSE)
Tcm_SP_da <- FindMarkers(CARCT_sub_SP , ident.1 = "CD8 Tcm1_3", ident.2 = "CD8 Tcm1_0", verbose = FALSE)

#alternative ways to find DE expression across conditions within cluster
CARCT_sub_SP <- subset(x = CARCT_sub_de, subset = tissue == "Spleen")
de <- data.frame()
for(celltype in unique(CARCT_sub_SP$celltype)){
  CARCT_sub_SP2 <- subset(x = CARCT_sub_SP, subset = celltype == celltype)
  Idents(CARCT_sub_SP2) <- CARCT_sub_SP2$Sample
  tmp <- FindMarkers(CARCT_sub_SP2 , ident.1 = 'SP_39B', ident.2 = 'SP_39A', verbose = FALSE)
  de <- rbind(de, data.frame(Celltype = celltype, Gene = rownames(tmp), tmp)
  )
}
de_SP <- de[(de$pct.1 > 0.1) & (de$p_val_adj < 0.01) & (abs(de$avg_log2FC) > 0.5),]
##subset BM samples
#Tcm
CARCT_sub_BM <- subset(x = CARCT_sub_de, subset = tissue == "BM")
Tcm_BM_ca <- FindMarkers(CARCT_sub_BM , ident.1 = "CD8 Tcm_2", ident.2 = "CD8 Tcm_0", verbose = FALSE)
Tcm_BM_ba <- FindMarkers(CARCT_sub_BM , ident.1 = "CD8 Tcm_1", ident.2 = "CD8 Tcm_0", verbose = FALSE)
Tcm_BM_da <- FindMarkers(CARCT_sub_BM , ident.1 = "CD8 Tcm_3", ident.2 = "CD8 Tcm_0", verbose = FALSE)
Tcm_BM_cd <- FindMarkers(CARCT_sub_BM , ident.1 = "CD8 Tcm_2", ident.2 = "CD8 Tcm_3", verbose = FALSE)
Tcm_BM_cb <- FindMarkers(CARCT_sub_BM , ident.1 = "CD8 Tcm_2", ident.2 = "CD8 Tcm_1", verbose = FALSE)
Teff_BM_cd <- FindMarkers(CARCT_sub_BM , ident.1 = "CD4 Teff_2", ident.2 = "CD4 Teff_3",logfc.threshold = 0, verbose = FALSE)
de_Teff_BM_cd  <- Teff_BM_cd [(Teff_BM_cd $pct.1 > 0.1) & (Teff_BM_cd $p_val_adj < 0.01) & (abs(Teff_BM_cd $avg_log2FC) > 0.5),]
#
de_Teff_BM_cd $ gene <- row.names(de_Teff_BM_cd)
Idents(CARCT_sub_BM) <- CARCT_sub_BM$Sample
de_Teff_BM_cd <- de_Teff_BM_cd[with(de_Teff_BM_cd, order(avg_log2FC)),]

DoHeatmap(subset(CARCT_sub_BM, downsample = 1000,subset = celltype=="CD4 Teff" & Sample %in%c("BM_39C","BM_39D")), 
          group.by = "Sample", features = de_Teff_BM_cd$gene )

#make valcano plot
p1 <- ggplot(data=Teff_BM_cd, aes(x=avg_log2FC,y=-log10(p_val_adj),label = gene))+
  geom_point(color = 'grey')+
  geom_point(data = Teff_BM_cd[(Teff_BM_cd$avg_log2FC > 0.5) & (Teff_BM_cd$p_val_adj < 0.01),], color = 'salmon') +
  geom_point(data = Teff_BM_cd[(Teff_BM_cd$avg_log2FC < -0.5) & (Teff_BM_cd$p_val_adj < 0.01),], color = 'cornflowerblue') +
  ggrepel::geom_text_repel(data = Teff_BM_cd[(abs(Teff_BM_cd$avg_log2FC) > 0.5) & (Teff_BM_cd$p_val_adj < 0.01),]) +
  theme_classic()
ggsave(plot = p1, filename = "CD4Teff_cd.pdf", dpi = 300, width = 8, height = 6, units = 'in')



